default: &default
  adapter: postgresql
  host: localhost
  username: athlete
  password: 123456
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: too_fit_to_quit_dev

test:
  <<: *default
  database: too_fit_to_quit_test
